# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('cnpj', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
