# Generated by Django 2.1.2 on 2018-11-11 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(choices=[('tecnico', 'Técnico'), ('supervisor', 'Supervisor')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('unidade_de_medida', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('conferido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Cliente')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Empreendimento')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Indicador')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('modelo', models.CharField(choices=[('fixo', 'Fixo'), ('mensal', 'Mensal')], max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='indicador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.TipoIndicador'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
