# Generated by Django 2.1.2 on 2018-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_auto_20181120_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
