# Generated by Django 2.1.2 on 2018-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0005_auto_20181120_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='unidade_de_medida',
            new_name='campo1',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='valor',
            new_name='valor_campo_1',
        ),
        migrations.AddField(
            model_name='indicador',
            name='campo2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='valor_campo_2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
