# Generated by Django 2.1.2 on 2018-11-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0006_auto_20181121_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo',
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='codigo',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
