# Generated by Django 2.1.2 on 2018-11-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0007_auto_20181125_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
