# Generated by Django 2.2.5 on 2019-09-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0009_auto_20181211_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='campo1',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='campo2',
        ),
        migrations.AddField(
            model_name='indicador',
            name='unit',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='CampoIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=500)),
                ('type_value', models.CharField(choices=[('number', 'Aberta (Número inteiro)'), ('float', 'Aberta (Número decimal)'), ('text', 'Aberta (Texto)'), ('select', 'Múltipla escolha')], max_length=500)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Indicador')),
            ],
        ),
    ]
