# Generated by Django 2.2.5 on 2019-10-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0010_auto_20190923_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='conferido_por',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='valor_campo_1',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='valor_campo_2',
        ),
        migrations.AlterField(
            model_name='campoindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='indicadores.Indicador'),
        ),
    ]
