# Generated by Django 2.2.5 on 2019-10-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0011_auto_20191006_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
