# Generated by Django 2.2.5 on 2019-10-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0012_delete_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('campo_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.CampoIndicador')),
                ('conferido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Cliente')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Empreendimento')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Referencia')),
            ],
        ),
    ]
