# Generated by Django 2.2.5 on 2019-10-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0013_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='indicadores.TipoIndicador'),
        ),
    ]
