# Generated by Django 2.2.5 on 2019-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0014_auto_20191006_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoindicador',
            name='type_value',
            field=models.CharField(choices=[('number', 'Aberta (Número inteiro)'), ('number', 'Aberta (Número decimal)'), ('text', 'Aberta (Texto)'), ('select', 'Múltipla escolha')], max_length=500),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='valor',
            field=models.TextField(default=''),
        ),
    ]
