# Generated by Django 2.2.5 on 2019-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0016_campoindicador_nome_variavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campoindicador',
            name='indicador',
        ),
        migrations.AddField(
            model_name='indicador',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipoindicador',
            name='campos',
            field=models.ManyToManyField(blank=True, to='indicadores.CampoIndicador'),
        ),
    ]
