# Generated by Django 2.2.5 on 2019-10-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0019_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCalculado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Empreendimento')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Indicador')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Referencia')),
            ],
        ),
    ]
