# Generated by Django 2.2.5 on 2019-10-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0020_resultadocalculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='calculado',
            field=models.BooleanField(default=False),
        ),
    ]
