# Generated by Django 2.2.5 on 2019-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0023_referencia_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='endereco',
            field=models.TextField(default=''),
        ),
    ]
