# Generated by Django 2.2.4 on 2020-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0025_resultado_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
