# Generated by Django 2.2.4 on 2020-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0026_referencia_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencia',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='indicador',
            name='campos_necessarios',
            field=models.CharField(default='', max_length=500, verbose_name='Campos necessários (Não mexer, atualizado automaticamente)'),
        ),
    ]
