# Generated by Django 2.2 on 2020-07-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0028_auto_20200702_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='logenvioderesultado',
            name='data_e_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='data_e_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadocalculado',
            name='data_e_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='RegitroErrosEnvios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('razao', models.TextField(default='')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Cliente')),
                ('empreendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Empreendimento')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Referencia')),
            ],
        ),
    ]
